<?php

namespace ContainerTHzA4NA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cOiAsDO.App\Controller\PostController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cOiAsDO.App\\Controller\\PostController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'serializer' => '?',
            'postRepository' => 'App\\Repository\\PostRepository',
        ]))->withContext('App\\Controller\\PostController::index()', $container);
    }
}
