<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerESUb2SR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerESUb2SR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerESUb2SR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerESUb2SR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerESUb2SR\App_KernelDevDebugContainer([
    'container.build_hash' => 'ESUb2SR',
    'container.build_id' => '2db51d06',
    'container.build_time' => 1742379830,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerESUb2SR');
