<?php

namespace ContainerESUb2SR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0I3qeloService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0I3qelo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0I3qelo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\PostController::index' => ['privates', '.service_locator.cOiAsDO.App\\Controller\\PostController::index()', 'getPostControllerindexService', true],
            'App\\Controller\\PostController::show' => ['privates', '.service_locator.bYd9OZr.App\\Controller\\PostController::show()', 'getPostControllershowService', true],
            'App\\Controller\\PostController::create' => ['privates', '.service_locator.GL345QQ.App\\Controller\\PostController::create()', 'getPostControllercreateService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\PostController:index' => ['privates', '.service_locator.cOiAsDO.App\\Controller\\PostController::index()', 'getPostControllerindexService', true],
            'App\\Controller\\PostController:show' => ['privates', '.service_locator.bYd9OZr.App\\Controller\\PostController::show()', 'getPostControllershowService', true],
            'App\\Controller\\PostController:create' => ['privates', '.service_locator.GL345QQ.App\\Controller\\PostController::create()', 'getPostControllercreateService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\PostController::index' => '?',
            'App\\Controller\\PostController::show' => '?',
            'App\\Controller\\PostController::create' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\PostController:index' => '?',
            'App\\Controller\\PostController:show' => '?',
            'App\\Controller\\PostController:create' => '?',
        ]);
    }
}
