<?php

namespace ContainerESUb2SR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bYd9OZr.App\Controller\PostController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bYd9OZr.App\\Controller\\PostController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
        ], [
            'postRepository' => 'App\\Repository\\PostRepository',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\PostController::show()', $container);
    }
}
